site_name:        AxisArrays.jl
repo_url:         https://github.com/JuliaArrays/AxisArrays.jl
site_description: Performant arrays where each dimension can have a named axis with values
site_author:      mbauman 

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Reference: reference.md
